# Generated by Django 3.1 on 2023-01-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_certificationrequest_unique_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
