# Generated by Django 4.0.8 on 2023-10-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0004_auto_20230116_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
